import {PrismaClient} from "@prisma/client";const p=new PrismaClient();
const ingredients=[
["Oignon","oignon","Fruits & légumes","pièce"],["Ail","ail","Fruits & légumes","gousse"],["Tomate","tomate","Fruits & légumes","g"],["Carotte","carotte","Fruits & légumes","pièce"],["Champignon","champignon","Fruits & légumes","g"],["Citron","citron","Fruits & légumes","pièce"],["Poulet","poulet","Boucherie","g"],["Saumon","saumon","Poissonnerie","g"],["Œuf","oeuf","Produits frais","pièce"],["Beurre","beurre","Produits frais","g"],["Crème","creme","Produits frais","ml"],["Fromage","fromage","Produits frais","g"],["Lait","lait","Produits frais","ml"],["Farine","farine","Épicerie","g"],["Riz","riz","Épicerie","g"],["Pâtes","pates","Épicerie","g"],["Haricots rouges","haricots-rouges","Épicerie","g"],["Sucre","sucre","Épicerie","g"],["Curry","curry","Épicerie","c. à soupe"],["Pain burger","pain-burger","Boulangerie","pièce"]] as const;
const recipes=[
{name:"Curry de poulet",slug:"curry-de-poulet",cat:"Plat",mins:[15,30,0],tags:"familial,épicé",ings:[["Poulet",600,"g"],["Oignon",2,"pièce"],["Ail",2,"gousse"],["Crème",250,"ml"],["Curry",2,"c. à soupe"],["Riz",300,"g"]],steps:[["COUPER","Couper le poulet et émincer les oignons."],["CUIRE_POELE","Faire revenir le poulet, l’oignon et l’ail.",10],["MIJOTER","Ajouter la crème et le curry, puis mijoter.",15],["SERVIR","Servir avec le riz cuit."]] },
{name:"Quiche lorraine",slug:"quiche-lorraine",cat:"Plat",mins:[20,35,0],tags:"classique,familial",ings:[["Farine",250,"g"],["Beurre",125,"g"],["Œuf",4,"pièce"],["Crème",250,"ml"],["Fromage",100,"g"]],steps:[["MELANGER","Préparer la pâte avec la farine et le beurre."],["FOUETTER","Fouetter les œufs et la crème."],["ASSEMBLER","Garnir la pâte et parsemer de fromage."],["CUIRE_FOUR","Cuire au four.",35,180]]},
{name:"Pâtes carbonara",slug:"pates-carbonara",cat:"Plat",mins:[10,15,0],tags:"rapide,italien",ings:[["Pâtes",400,"g"],["Œuf",4,"pièce"],["Fromage",120,"g"],["Crème",100,"ml"]],steps:[["BOUILLIR","Cuire les pâtes."],["FOUETTER","Mélanger les œufs, la crème et le fromage."],["ASSEMBLER","Hors du feu, mélanger avec les pâtes."]]},
{name:"Soupe de légumes",slug:"soupe-de-legumes",cat:"Soupe",mins:[20,35,0],tags:"léger,végétarien",ings:[["Oignon",2,"pièce"],["Ail",1,"gousse"],["Carotte",5,"pièce"],["Tomate",300,"g"]],steps:[["COUPER","Couper tous les légumes."],["BOUILLIR","Cuire dans l’eau salée.",30],["MIXER","Mixer jusqu’à obtenir une soupe lisse."]]},
{name:"Burger maison",slug:"burger-maison",cat:"Plat",mins:[25,15,0],tags:"convivial",ings:[["Pain burger",4,"pièce"],["Oignon",1,"pièce"],["Tomate",250,"g"],["Fromage",120,"g"]],steps:[["COUPER","Émincer l’oignon et trancher les tomates."],["CUIRE_POELE","Cuire les garnitures."],["ASSEMBLER","Monter les burgers."]]},
{name:"Saumon au four",slug:"saumon-au-four",cat:"Plat",mins:[10,20,0],tags:"poisson,facile",ings:[["Saumon",600,"g"],["Citron",1,"pièce"],["Ail",2,"gousse"],["Beurre",30,"g"]],steps:[["ASSEMBLER","Déposer le saumon avec citron, ail et beurre."],["CUIRE_FOUR","Cuire au four.",20,180]]},
{name:"Risotto aux champignons",slug:"risotto-champignons",cat:"Plat",mins:[15,35,0],tags:"italien,végétarien",ings:[["Riz",320,"g"],["Champignon",400,"g"],["Oignon",1,"pièce"],["Beurre",40,"g"],["Fromage",80,"g"]],steps:[["EMINCER","Émincer l’oignon et les champignons."],["CUIRE_POELE","Faire revenir au beurre."],["MIJOTER","Ajouter progressivement l’eau au riz.",25],["MELANGER","Incorporer le fromage."]]},
{name:"Chili sin carne",slug:"chili-sin-carne",cat:"Plat",mins:[15,40,0],tags:"végétarien,épicé",ings:[["Haricots rouges",500,"g"],["Tomate",600,"g"],["Oignon",2,"pièce"],["Ail",2,"gousse"],["Riz",300,"g"]],steps:[["EMINCER","Émincer l’oignon et l’ail."],["MIJOTER","Mijoter avec tomates et haricots.",35],["SERVIR","Servir avec le riz."]]},
{name:"Cheesecake",slug:"cheesecake",cat:"Dessert",mins:[25,50,240],tags:"dessert,gourmand",ings:[["Beurre",100,"g"],["Fromage",600,"g"],["Sucre",150,"g"],["Œuf",3,"pièce"],["Citron",1,"pièce"]],steps:[["ECRASER","Écraser la base et mélanger au beurre."],["FOUETTER","Fouetter fromage, sucre, œufs et citron."],["CUIRE_FOUR","Cuire au four.",50,160],["REFRIGERER","Réfrigérer avant de servir.",240]]},
{name:"Tarte au citron",slug:"tarte-au-citron",cat:"Dessert",mins:[30,25,120],tags:"dessert,acidulé",ings:[["Farine",250,"g"],["Beurre",150,"g"],["Sucre",130,"g"],["Œuf",3,"pièce"],["Citron",3,"pièce"]],steps:[["MELANGER","Préparer la pâte."],["CUIRE_FOUR","Précuire la pâte.",15,180],["FOUETTER","Fouetter œufs, sucre et citron."],["CHAUFFER","Épaissir la crème à feu doux."],["REFROIDIR","Garnir puis laisser refroidir.",120]]}
] as const;
async function main(){await p.shoppingItemState.deleteMany();await p.mealSlot.deleteMany();await p.recipe.deleteMany();await p.ingredient.deleteMany();for(const [name,slug,category,defaultUnit] of ingredients)await p.ingredient.create({data:{name,slug,category,defaultUnit}});for(const r of recipes){const comp=await p.recipe.create({data:{name:r.name,slug:r.slug,description:`Une recette ${r.tags.split(",")[0]} simple et savoureuse.`,category:r.cat,defaultServings:4,prepMinutes:r.mins[0],cookMinutes:r.mins[1],restMinutes:r.mins[2],tags:r.tags,components:{create:{name:"Préparation",order:1}}},include:{components:true}});for(let i=0;i<r.ings.length;i++){const [name,quantity,unit]=r.ings[i];const ing=await p.ingredient.findUniqueOrThrow({where:{name}});await p.recipeIngredient.create({data:{recipeId:comp.id,ingredientId:ing.id,componentId:comp.components[0].id,quantity,unit,order:i}})}for(let i=0;i<r.steps.length;i++){const [actionType,description,durationMinutes,temperatureC]=r.steps[i];await p.recipeStep.create({data:{recipeId:comp.id,componentId:comp.components[0].id,order:i+1,actionType,description,durationMinutes:durationMinutes??null,temperatureC:temperatureC??null}})}}const all=await p.recipe.findMany();const monday=new Date();monday.setHours(12,0,0,0);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));for(let d=0;d<7;d++){for(const [j,mealType] of ["LUNCH","DINNER"].entries()){const date=new Date(monday);date.setDate(monday.getDate()+d);await p.mealSlot.create({data:{date,mealType,recipeId:all[(d*2+j)%all.length].id,servings:d%3===0?6:4}})}}}
main().finally(()=>p.$disconnect());
